/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-06-23 20:43:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class editArticle2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.js\"\r\n");
      out.write("			integrity=\"sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=\"\r\n");
      out.write("			crossorigin=\"anonymous\">\r\n");
      out.write("	</script>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/13deb536c6.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function () {\r\n");
      out.write("			$(\"#header\").load(\"header.html\");\r\n");
      out.write("			$(\"#footer\").load(\"footer.html\");\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"script/script.js\" type=\"text/javascript\" defer=\"defer\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Edit Article</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"imgs/tech.png\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"preview()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"font\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("    <div id=\"header\"></div>\r\n");
      out.write("   	<div class=\"header-spacing\"></div>\r\n");
      out.write("       <link rel=\"stylesheet\" href=\"styles/style.css\">\r\n");
      out.write("\r\n");
      out.write("       <form onsubmit=\"Submit()\" class=\"needs-validation\" enctype=\"multipart/form-data\" novalidate method=\"post\">\r\n");
      out.write("\r\n");
      out.write("        <div class = \"form-holder\">\r\n");
      out.write("            <h2 style=\"font-size: 45px;\">Edit Article...</h2>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("				<input type=\"hidden\" id=\"article_id\" name=\"article_id\" value=\"");
 out.println(request.getParameter("article_id")); 
      out.write("\">\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("                <div class=\"upload-image-container\">\r\n");
      out.write("                    <img id=\"output\" src =\"");
 out.println(request.getAttribute("edit_image_path")); 
      out.write("\" class=\"img-fluid news-img\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <br>\r\n");
      out.write("                <label for=\"file\" style=\"cursor: pointer;\" class=\"form-label upload-image\"><i class=\"fa-solid fa-arrow-up-from-bracket fa-lg\"></i> &nbsp;&nbsp;Upload an image</label>\r\n");
      out.write("                <input type=\"file\"  accept=\"image/gif, image/jpeg, image/jpg, image/png\" name=\"file\" id=\"file\" onchange=\"loadFile(event)\" hidden>\r\n");
      out.write("				<div class=\"invalid-feedback\" style=\"margin-bottom:30px\"> \r\n");
      out.write("					Upload an image\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"row g-2 input-row\">\r\n");
      out.write("                    <div class=\"col\" style=\"padding-right: 20px;\">\r\n");
      out.write("\r\n");
      out.write("                        <label for = \"title\" class=\"form-label\" style=\"opacity:70%;\">Title</label> \r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                            <input name=\"title\" type = \"text\" class = \"form-control\"  id = \"title\" placeholder=\"Write your title...\" minlength=\"10\" maxlength=\"200\" onkeyup=\"titleLimit()\" pattern=\"^[^<>]*$\" value=\"");
 out.println(request.getAttribute("edit_title")); 
      out.write("\" required>\r\n");
      out.write("                            <div class=\"invalid-feedback\">\r\n");
      out.write("                                Title should be atleast 10 characters long.\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-1\">\r\n");
      out.write("                        <div id=\"title-limit\" class=\"limit\">200</div>\r\n");
      out.write("   \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row g-2 input-row\">\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <label for=\"article\" class=\"form-label\" style=\"opacity:70%;\">Article</label>\r\n");
      out.write("                        <textarea name=\"article\" class=\"form-control\" id=\"article\" placeholder=\"Write your article...\" rows=\"20\" maxlength=\"5000\" minlength=\"100\" onkeyup=\"articleLimit()\"  required>");
 out.println(request.getAttribute("edit_body")); 
      out.write("</textarea>\r\n");
      out.write("                \r\n");
      out.write("                        <div class=\"invalid-feedback\">\r\n");
      out.write("                            Article should be atleast 100 characters long.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-1\">\r\n");
      out.write("                        <div id=\"article-limit\" class=\"limit\">5000</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row g-2 input-row\">\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <label for=\"tags\" class=\"form-label\" style=\"opacity:70%;\">Tags</label>\r\n");
      out.write("                        <input name=\"tags\" class=\"form-control\" id=\"tags\" style=\"width: 50%;\" pattern=\"(#+[a-zA-Z0-9(_)]{1,})*\" placeholder=\"Eg. #gaming#pc#gpu\" value=\"");
 out.println(request.getAttribute("edit_tags")); 
      out.write("\" required/>\r\n");
      out.write("                \r\n");
      out.write("                        <div class=\"invalid-feedback\">\r\n");
      out.write("                            Tag needed\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-sm\" style=\"padding: 20px 1px;\">\r\n");
      out.write("                <div class=\"form-floating mb-3\" >\r\n");
      out.write("                    <div onclick=\"preview()\" class=\"btn bamboo-outline form-submit\">Preview </div>     \r\n");
      out.write("                    <div type=\"button\" class=\"red-button\" style=\"margin-top:15px\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModalCenter\">Delete Article</div>\r\n");
      out.write("                    <!-- Modal -->\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                        <div class=\"modal fade\" id=\"exampleModalCenter\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("                            <div class=\"modal-content\">\r\n");
      out.write("                               \r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                <h4>Delete this Article?</h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"modal-footer\">\r\n");
      out.write("                                <div type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">No</div>\r\n");
      out.write("                                <div type=\"button\" onclick=\"Delete()\" class=\"btn btn-danger\">Yes</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"preview-holder\" id=\"preview\">\r\n");
      out.write("            <h2 style=\"font-size: 45px;\">Preview...</h2>\r\n");
      out.write("            <hr>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"article-container\">\r\n");
      out.write("                <h1 class=\"title-article\" id=\"title-preview\"></h1>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"article-image-container\">\r\n");
      out.write("                    <img src=\"");
 out.println(request.getAttribute("edit_image_path")); 
      out.write("\" id=\"output2\" width=\"750px\" class=\"img-fluid\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"article-writer\">\r\n");
      out.write("                    John Doe &nbsp; | &nbsp;  11:49 Sun, 11 Jun 2023\r\n");
      out.write("                </div>\r\n");
      out.write("            <div class=\"article-body\" id=\"body-preview\"></div>\r\n");
      out.write("            <div class=\"tags-container\" id=\"tags_container\">\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                        <a class=\"tag\">#tags</a>\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <button type=\"submit\" class=\"btn bamboo form-submit\" >Submit&nbsp;&nbsp;<i class=\"fa-solid fa-arrow-right fa-lg\"></i></button>\r\n");
      out.write("            <br>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    // Example starter JavaScript for disabling form submissions if there are invalid fields\r\n");
      out.write("(() => {\r\n");
      out.write("'use strict'\r\n");
      out.write("\r\n");
      out.write("// Fetch all the forms we want to apply custom Bootstrap validation styles to\r\n");
      out.write("const forms = document.querySelectorAll('.needs-validation')\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// Loop over them and prevent submission\r\n");
      out.write("Array.from(forms).forEach(form => {\r\n");
      out.write("  form.addEventListener('submit', event => {\r\n");
      out.write("\r\n");
      out.write("    if (!form.checkValidity()) {\r\n");
      out.write("      event.preventDefault()\r\n");
      out.write("      event.stopPropagation()\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    form.classList.add('was-validated')\r\n");
      out.write("\r\n");
      out.write("  }, false)\r\n");
      out.write("  \r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("})()\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    function preview(){\r\n");
      out.write("        var article = document.getElementById('article').value;\r\n");
      out.write("        var title = document.getElementById('title').value;\r\n");
      out.write("        var tags = document.getElementById('tags').value;\r\n");
      out.write("        var title_preview = document.getElementById('title-preview');\r\n");
      out.write("        var body_preview = document.getElementById('body-preview');\r\n");
      out.write("        var tags_container = document.getElementById('tags_container');\r\n");
      out.write("        var preview = document.getElementById('preview');\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        if(article!=\"\")\r\n");
      out.write("            body_preview.innerHTML = article;\r\n");
      out.write("        \r\n");
      out.write("        if(title!=\"\")\r\n");
      out.write("            title_preview.innerHTML = title;\r\n");
      out.write("        \r\n");
      out.write("        if(tags!=\"\")\r\n");
      out.write("        {\r\n");
      out.write("        	tags_container.innerHTML=\"\";\r\n");
      out.write("            var each_tags = tags.split('#');\r\n");
      out.write("            for (var i = 1; i < each_tags.length;i++) {\r\n");
      out.write("                tags_container.innerHTML =  tags_container.innerHTML + \"<a class='tag'>#\"+each_tags[i]+\"</a>\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function Delete(){\r\n");
      out.write("\r\n");
      out.write("        var article_id = document.getElementById('article_id').value\r\n");
      out.write("        \r\n");
      out.write("        var http = new XMLHttpRequest();\r\n");
      out.write("        http.open(\"POST\", \"DeleteArticle\", true);\r\n");
      out.write("        http.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("        var params = \"delete=\" + article_id; \r\n");
      out.write("        http.send(params);\r\n");
      out.write("        \r\n");
      out.write("        window.location.href = \"postDelete.html\";\r\n");
      out.write("   }\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"footer\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
